### ISSUE TITLE
Publish on F-Droid?

### ISSUE THREAD

**Issue by IzzySoft** [KeyLo99/k3pler#2]
As far as I can see, there are no show-stoppers for publishing your app on F-Droid (which is **THE** place for Android FOSS apps). Assuming you are interested, I've [opened a Request For Packaging](https://gitlab.com/fdroid/rfp/issues/740) ("RFP") for your app – so if you agree, F-Droid would build your app from your sources, and include it with its index (see [here](https://f-droid.org/)).

Would you support that? Thanks in advance!

**Comment by orhun** [comment]
Hi.
F-Droid looks suitable for this open-source app. Ofc you can build and share.
In addition here's the Google Play link: https://play.google.com/store/apps/details?id=com.tht.k3pler

**Comment by IzzySoft** [comment]
Thanks a lot, @KeyLo99! Until it's build and available in the official repo, I just made it available in mine: http://apt.izzysoft.de/fdroid/index/apk/com.tht.k3pler (so it can already be found with the F-Droid client if the user has my repo enabled in it).

**Comment by IzzySoft** [comment]
@KeyLo99 the scanner bot just ran and found a minor security issue with your gradlew, [see here](https://gitlab.com/fdroid/rfp/issues/740#note_107005497). Not relevant for the F-Droid build (which works a bit different) – but thought you might wish to know for yours.

**Comment by IzzySoft** [comment]
@KeyLo99 I just notice [tags](https://github.com/KeyLo99/k3pler/releases) are missing. Our "builders" very much prefer them (makes it easier to package the correct commit – and to identify updates). Could you please use them?

**Comment by orhun** [comment]
@IzzySoft There you go. [>](https://github.com/KeyLo99/k3pler/releases)

**Comment by IzzySoft** [comment]
Thanks a lot! Pinged our "integrators" to pick it up. And adjusted my updater to fetch the APK from the tags :smiley:

**Comment by orhun** [comment]
Hey there! How can I update the APK on F-Droid?

**Comment by IzzySoft** [comment]
@KeyLo99 just tag a new release. [Metadata say](https://gitlab.com/fdroid/fdroiddata/blob/master/metadata/com.tht.k3pler.yml#L29) that will be noticed, fetched and built automatically (then pushed into the review queue for approval, signing and finally publication).

Taken literally: you cannot update the APK, as F-Droid builds it from source :wink:

**Comment by IzzySoft** [comment]
No idea why it's not even picked up in Metadata yet. Sometimes it takes a couple of days. Should above link still not show the new version within a week, feel free to ping me again (or ask on IRC `#fdroid` at freenode yourself; I'm not involved nor familiar with builds, so that's what I'd do then anyway).

**Comment by IzzySoft** [comment]
Just to let you know you now made updates impossible in [this commit](https://github.com/orhun/k3pler/commit/64b57bb9da692ccc78b2acf8586080b2d6c088a6#diff-39e7d8c00954e920b98e7636f0ac30b2): changing the package ID is a very bad idea. There can't and won't be any future updates in F-Droid. Users must re-install your app.

Was that intended? Then you need to apply for a new listing of the new package name. If not: either revert the change of package name back to what it was, or add a specific build flavor explicitly setting `applicationId "com.tht.k3pler"` so we can point our build process to that.

Reference: https://gitlab.com/fdroid/fdroiddata/issues/1820
